name: Check markup links
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      docs: ${{ steps.filter.outputs.docs || 'true' }}
    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d  # v4.0.1
        id: filter
        if: github.event_name == 'pull_request'
        with:
          filters: |
            docs:
              - 'docs/**'
  markdown-link-check:
    needs: changes
    if: needs.changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Check Markup Links
      run: |
        python python/tools/markdown_link_check.py docs
